### PR TITLE
Junit tests

### PR DESCRIPTION
**Pull request by Lucas-ws**
Added a way to test Board! We don't have much to test right now but we will soon! Please also enjoy the Game restructure which makes it much more readable. Cheers.

### CODE REVIEW

**Comment by TomasBorsje** [comment]
Looks good.

**Comment by TomasBorsje** [comment]
On second thought, you're trying to merge into main, not dev. Is this intentional?

**Comment by Lucas-ws** [comment]
> On second thought, you're trying to merge into main, not dev. Is this intentional?

My apologies. Main is the default branch you see... Fixed~!

**Comment by TomasBorsje** [comment]
Looks wonderful! Perfect! Pristine! Yippee!
Merged.

**Comment by Lucas-ws** [comment]
Legend 👍

**Pull request merged**
